### ISSUE TITLE
Bone Shin.01 changes position deforming the mesh.

### ISSUE THREAD

**Issue by 1Snakel** [Arminando/GameRig#14]
Hi! Thanks for your great work with rigify.

For some reason, it seems that the bone Shin.01 shifts alone when you parent it to your model. Which causes some distortion on the model
[BUG.zip](https://github.com/Arminando/GameRig/files/7566613/BUG.zip)

![Screenshot_20211118_200631](https://user-images.githubusercontent.com/11818756/142510950-fd88443a-06e1-4279-9ffc-1e0f00b4fe9f.png)
![Screenshot_20211118_200620](https://user-images.githubusercontent.com/11818756/142510954-924d825c-4d03-400b-85b5-ef237c8dd78f.png)

**Comment by Arminando** [comment]
Sorry for the really late reply.
I checked the file and it seems that the algorithm that is guessing what the bend axis for the leg is getting a bit confused. I suggest changing the rotation axis to X Manual on the legs. That should fix things. 

![image](https://user-images.githubusercontent.com/32486173/147851004-3f8863bf-2211-4fa1-95b8-d5b3ea413242.png)
