### ISSUE TITLE
missing 1 required positional argument: 'obj'

### ISSUE THREAD

**Issue by alexchoin** [Arminando/GameRig#15]
I created a game basic human rig, clicked on the metarig,  hit generate new rig and get:

`Generation has thrown an exception: _Generator__rename_org_bones() missing 1 required positional argument: 'obj'`

some stuff is created but I see no controls

**Comment by Arminando** [comment]
Which version of Blender did you try this on? Any chance you could send me the file with the metarig so I can dig through it to find out what is broken?

**Comment by alexchoin** [comment]
I was using Blender 2.91, I'll try using the listed 2.92

[](https://drive.google.com/file/d/1c-VWne065dq7n6Y5IR2ObNSj5F9dj2G4/view?usp=sharing) here's the file anyway. 

Thanks
