### ISSUE TITLE
face.basic_tongue is backwards

### ISSUE THREAD

**Issue by Jorhlok** [Arminando/GameRig#19]
I noticed the new tongue has the whole tongue chain reversed when I tried to convert from one to the other and the main control ended up in the back of the throat.

A quick work around was to select the whole tongue chain in edit mode and use Armature>Switch Direction

**Comment by Arminando** [comment]
This was intentional actually. I adjusted the tongue component so that the chain is oriented in a way that works better for game engines.
Maybe I should make two tongue versions. One inverted and one the same as the non game version.
