### ISSUE TITLE
Which control bone should i use?

### ISSUE THREAD

**Issue by HEKEPOIU** [Arminando/GameRig#20]
I use Game Rig feature set generated the base human preset, and it generated two root control (one is default rigify root control, another is diamond shape control).

If i want to make root motion to game engine, which control bone should I Use?

**Comment by Arminando** [comment]
You can use either. The root bone will follow both of them. If you want to keep it simple, you can ignore the diamond control and use the default rigify root.

**Comment by HEKEPOIU** [comment]
oh Thanks!
