### ISSUE TITLE
Broken in 3.5

### ISSUE THREAD

**Issue by Spazi-dev** [Arminando/GameRig#25]
![image](https://user-images.githubusercontent.com/62376411/235614360-4b1d0b63-ef9c-4636-885c-0e0ef1a2f4a9.png)

GameRig menus are empty or missing. N-key tool menu's GameRig tab missing entirely.

**Comment by arminHalac** [comment]
Which version of Blender are you using?

**Comment by Spazi-dev** [comment]
3.5.0, allegedly in 3.4 and 3.3 GameRig works okay, but I don't have them at hand to confirm.

**Comment by Arminando** [comment]
[GameRig.zip](https://github.com/Arminando/GameRig/files/11524238/GameRig.zip)
Here is a version that works in 3.5. Can you give it a test and let me know if it works?

**Comment by Spazi-dev** [comment]
Seems to work! List objects appear again and no apparent issues with some quick rigging ^^

**Comment by Arminando** [comment]
Fantastic. Thank you for testing. I will make a proper release ASAP.
