### ISSUE TITLE
The addon does not support blender 3.5.1

### ISSUE THREAD

**Issue by iillya** [Arminando/GameRig#27]
The addon does not support blender 3.5.1.Can you update it？

**Comment by Arminando** [comment]
[GameRig.zip](https://github.com/Arminando/GameRig/files/11524235/GameRig.zip)
Here is the updated version. Can you test and let me know if issues are fixed?

**Comment by iillya** [comment]
> [GameRig.zip](https://github.com/Arminando/GameRig/files/11524235/GameRig.zip) Here is the updated version. Can you test and let me know if issues are fixed?

Yes.The issues are fixed.Thanks for your work.
